# Site
repository: twg0/twg0.github.io
# favicon: images/favicon.ico

# Personal info
name: 서재혁
title: Backend Developer
email: fruit9370@naver.com
website: https://blog.naver.com/twg_0

# Social links
# twitter_username: jojoldu
github_username:  twg_0
# dribbble_username: jekyll
# facebook_username: jojoldu
# flickr_username: jekyll
# linkedin_username: jojoldu
# pinterest_username: jekyll
# youtube_username: UCSEOUzkGNCT_29EU_vnBYjg

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 을 이용하여 다양한 프로젝트를 시도하는 개발자입니다.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   여러 주제로 발표와 기고, 출판을 해왔습니다.
#    - [인프콘 2022 - 인프런 아키텍처의 과거, 현재 그리고 미래](https://www.youtube.com/watch?v=D_QH50UkX_4)
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
